name: CI
on:
  push:
    branches:
    - master
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn build
      uses: w9jds/firebase-action@master
    - name: Deploy
      if: success()
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

