name: CI

on:

  push:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: yarn build

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/firebase-deploy-action@maste
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
